%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.8 on {{2015,8,22},{22,20,32}}

-ifndef(example).
-define(example, true).

-define(example_gpb_version, "3.18.8").

-record('Short',
        {name,                          % = 1, string
         email                          % = 2, string (optional)
        }).

-endif.
