%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.8 on {{2015,8,22},{22,20,32}}

-ifndef(meta_proto).
-define(meta_proto, true).

-define(meta_proto_gpb_version, "3.18.8").

-record(meta,
        {type,                          % = 1, {enum,'meta.msgtype'}
         msg                            % = 2, bytes
        }).

-endif.
