%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.8 on {{2015,8,24},{21,16,16}}

-ifndef(math_calcul).
-define(math_calcul, true).

-define(math_calcul_gpb_version, "3.18.8").

-record(areaofcircle,
        {name,                          % = 1, string
         radius,                        % = 2, int32
         area,                          % = 3, int32 (optional)
         unit                           % = 4, string (optional)
        }).

-record(areaofsquare,
        {name,                          % = 1, string
         side,                          % = 2, int32
         area,                          % = 3, int32 (optional)
         unit                           % = 4, string (optional)
        }).

-record(areaofrectangle,
        {name,                          % = 1, string
         height,                        % = 2, int32
         width,                         % = 3, int32
         area,                          % = 4, int32 (optional)
         unit                           % = 5, string (optional)
        }).

-record(factorial,
        {name,                          % = 1, string
         number,                        % = 2, int32
         result                         % = 3, int32 (optional)
        }).

-endif.
