%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.8 on {{2015,8,22},{13,42,33}}

-ifndef(message).
-define(message, true).

-define(message_gpb_version, "3.18.8").

-record(location,
        {region,                        % = 1, string
         country                        % = 2, string
        }).

-record(person,
        {name,                          % = 1, string
         address,                       % = 2, string
         phone_number,                  % = 3, string
         age,                           % = 4, int32
         location                       % = 5, {msg,location} (optional)
        }).

-endif.
