%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.8 on {{2015,8,22},{13,42,33}}

-ifndef(short).
-define(short, true).

-define(short_gpb_version, "3.18.8").

-record(short,
        {name,                          % = 1, string
         email                          % = 2, string (optional)
        }).

-endif.
